module.exports = {
    PORT: process.env.PORT || 5000,
    NGROK_TUNNEL_URL: 'https://a53b3a61.ngrok.io',
    CURRENT_CONTENT_PATH: './content/current/',
    STORED_CONTENT_PATH: './content/stored/',
    LOG_PATH: `./log/` ,
    APP_LANGUAGE: 'en',
    MOVIEDB_IMAGE_BASE_URL: 'https://image.tmdb.org/t/p/',
    MOVIE_GENRE: [
      { id: 28, name: 'Action' },
      { id: 12, name: 'Adventure' }, 
      { id: 16, name: 'Animation' }, 
      { id: 35, name: 'Comedy' }, 
      { id: 80, name: 'Crime' }, 
      { id: 99, name: 'Documentary' }, 
      { id: 18, name: 'Drama' }, 
      { id: 10751, name: 'Family' }, 
      { id: 14, name: 'Fantasy' }, 
      { id: 36, name: 'History' }, 
      { id: 27, name: 'Horror' }, 
      { id: 10402, name: 'Music' }, 
      { id: 9648, name: 'Mystery' }, 
      { id: 10749, name: 'Romance' }, 
      { id: 878, name: 'Science Fiction' },
      { id: 10770, name: 'TV Film' },  
      { id: 53, name: 'Thriller' }, 
      { id: 10752, name: 'War' }, 
      { id: 37, name: 'Western' }
      ],
    NUMBER_RESULTS: 5,
    NUMBER_IMAGES: 4
  };